  CREATE TABLE "SYSTEM"."EMPLOYEES"
   ( "EMPLOYEE_ID" NUMBER(6,0),
 "FIRST_NAME" VARCHAR2(20 BYTE),
 "LAST_NAME" VARCHAR2(25 BYTE),
 "EMAIL" VARCHAR2(25 BYTE),
 "PHONE_NUMBER" VARCHAR2(20 BYTE),
 "HIRE_DATE" DATE,
 "JOB_ID" VARCHAR2(10 BYTE),
 "SALARY" NUMBER(8,2),
 "COMMISSION_PCT" NUMBER(2,2),
 "MANAGER_ID" NUMBER(6,0),
 "DEPARTMENT_ID" NUMBER(4,0)
   );
   
   ALTER TABLE "SYSTEM"."EMPLOYEES" 
   ADD CONSTRAINT "EMP_EMP_ID_PK" 
   PRIMARY KEY ("EMPLOYEE_ID");
   
   insert into employees values (123456, 'GODFREY','MENEZES','GOMENEZE@IN.IBM.COM','7875001234','01-JAN-2000','SNR ENGG',400000,0.2,12345,63);
   
   
      